### ISSUE TITLE
Not working with zellij 0.41.1

### ISSUE THREAD

**Issue by Wolfsrudel** [cristiand391/zj-quit#4]
![image](https://github.com/user-attachments/assets/ba72595d-4e2a-4618-8e29-ddca6e976ad9)

**Comment by cristiand391** [comment]
yep, we got a PR that (I think) will make it compatible with 0.41.1:
https://github.com/cristiand391/zj-quit/pull/3

**Comment by Eloquencere** [comment]
Yeah, facing the same issue

**Comment by cristiand391** [comment]
v0.3.1 is compatible with zellij 0.41.1:

https://github.com/cristiand391/zj-quit/releases/tag/0.3.1

Thanks again @dj95 for the quick fix 🙌🏼
